In [1]:
# A university monitors electricity usage of 4 hosteks over 7 days (mon to sun).
 
import numpy as np

In [2]:
#Task A1: Create a Numpy array electricity using np.random.randint.range(values between 120 and 650),(shape 4,7) and print the array.

electricity=np.random.randint(120,650,size=(4,7))
print("Electricity usage array:\n", electricity)

Electricity usage array:
 [[432 473 173 241 206 446 303]
 [382 130 176 287 562 597 320]
 [590 189 339 283 237 406 233]
 [613 365 426 458 243 224 470]]


In [3]:
#Task A2: Print Shape, Number of dimensions, Total number of elements and Data type of the array.

print("Shape of the array:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type of the array:", electricity.dtype)

Shape of the array: (4, 7)
Number of dimensions: 2
Total number of elements: 28
Data type of the array: int32


In [4]:
#Task B1: Find the average electricity usage per hostel, the maximum usage per hostel an identify which hostel has the highest average usage.

average_usage_per_hostel = np.mean(electricity, axis=1)
max_usage_per_hostel = np.max(electricity, axis=1)
highest_average_usage_hostel = np.argmax(average_usage_per_hostel)
print("Average electricity usage per hostel:", average_usage_per_hostel)
print("Maximum electricity usage per hostel:", max_usage_per_hostel)
print("Hostel with the highest average usage:", highest_average_usage_hostel)

Average electricity usage per hostel: [324.85714286 350.57142857 325.28571429 399.85714286]
Maximum electricity usage per hostel: [473 597 590 613]
Hostel with the highest average usage: 3


In [5]:
#Task B2: Calculate the total electricity consumption for each day and identify which day has the highest consumption.

total_consumption_per_day = np.sum(electricity, axis=0)
highest_consumption_day = np.argmax(total_consumption_per_day)
print("Total electricity consumption per day:", total_consumption_per_day)
print("Day with the highest consumption (0=Mon, 1=Tue, ..., 6=Sun):", highest_consumption_day)

Total electricity consumption per day: [2017 1157 1114 1269 1248 1673 1326]
Day with the highest consumption (0=Mon, 1=Tue, ..., 6=Sun): 0


In [6]:
#Task C1: Create a new array penalized usage such that
    #- Values > 550 -> multiply by 1.2
    #- All other values remain the same.

penalized_usage = np.where(electricity > 550, electricity * 1.2, electricity)
print("Penalized electricity usage array:\n", penalized_usage)

Penalized electricity usage array:
 [[432.  473.  173.  241.  206.  446.  303. ]
 [382.  130.  176.  287.  674.4 716.4 320. ]
 [708.  189.  339.  283.  237.  406.  233. ]
 [735.6 365.  426.  458.  243.  224.  470. ]]


In [7]:
#Task D1: Compare each hostel's daily usage with its own weekly average. Create a boolean matrix where:
    #- True: Above hostel average
    #- False: Below or equal to hostel average

hostel_average = np.mean(electricity, axis=1, keepdims=True)
above_average_matrix = electricity > hostel_average
print("Boolean matrix indicating above average usage:\n", above_average_matrix)

Boolean matrix indicating above average usage:
 [[ True  True False False False  True False]
 [ True False False False  True  True False]
 [ True False  True False False  True False]
 [ True False  True  True False False  True]]


In [8]:
#Task E1: Reshape the electricity data into single row representing weekly usage (shape 1,28) and print the reshaped array.

reshaped_weekly_usage = electricity.reshape(1, -1)
print("Reshaped weekly usage array (1,28):\n", reshaped_weekly_usage)

Reshaped weekly usage array (1,28):
 [[432 473 173 241 206 446 303 382 130 176 287 562 597 320 590 189 339 283
  237 406 233 613 365 426 458 243 224 470]]


In [9]:
#Task E2: Reshape the same data into 2 rows and 14 columns (shape 2,14). Ensure no data is lost or duplicated. Print the reshaped array.

reshaped_2_rows = electricity.reshape(2, 14)
print("Reshaped array (2,14):\n", reshaped_2_rows)

Reshaped array (2,14):
 [[432 473 173 241 206 446 303 382 130 176 287 562 597 320]
 [590 189 339 283 237 406 233 613 365 426 458 243 224 470]]


In [10]:
#Task F1: Create ref_backup = electricty
    # Create safe_backup = ref_backup.copy()
    # Modify one value in the original electricity array.
    # Observe which backups change.

ref_backup = electricity
safe_backup = ref_backup.copy()
electricity[0, 0] = 999  # Modify one value in the original array
print("Original electricity array after modification:\n", electricity)
print("Reference backup (ref_backup):\n", ref_backup)
print("Safe backup (safe_backup):\n", safe_backup)

Original electricity array after modification:
 [[999 473 173 241 206 446 303]
 [382 130 176 287 562 597 320]
 [590 189 339 283 237 406 233]
 [613 365 426 458 243 224 470]]
Reference backup (ref_backup):
 [[999 473 173 241 206 446 303]
 [382 130 176 287 562 597 320]
 [590 189 339 283 237 406 233]
 [613 365 426 458 243 224 470]]
Safe backup (safe_backup):
 [[432 473 173 241 206 446 303]
 [382 130 176 287 562 597 320]
 [590 189 339 283 237 406 233]
 [613 365 426 458 243 224 470]]
