In [1]:
import numpy as np

In [2]:
marks=np.array ([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])

In [3]:
#Task A1: Deternmine the shape of array.
   # find the Total Number of elements
   #Identify the data type of the elements

print("Shape of marks array:", marks.shape)
print("Total number of elements:", marks.size)
print("Data type of elements:", marks.dtype)

Shape of marks array: (5, 3)
Total number of elements: 15
Data type of elements: int64


In [4]:
#Task A2: Extract all the marks form the 2nd student
  # Extract all the marks for the 3rd subject across all students
  #Find the specific marks of student 1 in subject 2.

print("Marks of 2nd student:", marks[1,:])
print("Marks of 3rd subject across all students:", marks[:,2])
print("Marks of student 1 in subject 2:", marks[0,1])

Marks of 2nd student: [45 60 55]
Marks of 3rd subject across all students: [90 55 95 35 75]
Marks of student 1 in subject 2: 85


In [5]:
#Task B1: Calculate the average marks for each student.
    #Calculate the average marks for each subject.
    #Hint: Think about axis parameter.

average_marks_per_student=np.mean(marks,axis=1)
print("Average marks for each student:", average_marks_per_student)
average_marks_per_subject=np.mean(marks,axis=0)
print("Average marks for each subject:", average_marks_per_subject)

Average marks for each student: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Average marks for each subject: [61.2 69.4 70. ]


In [6]:
#Task B2: Identify and display the student whose marks are >=80.(display one by one)

students_with_high_marks=np.where(average_marks_per_student>=80)[0]+1

print("Students with average marks >=80:")
for student in students_with_high_marks:
    print(f"Student {student}" )

Students with average marks >=80:
Student 1
Student 3


In [7]:
#Task B3: The college decides to add 5 grace marks to every subject for every student.Update the array using broadcasting. 

marks_with_grace=marks+5
print("Marks after adding grace marks:\n", marks_with_grace)

Marks after adding grace marks:
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [8]:
#Task C1: Create a status matrix where:
    # mark>=50 ->1(Pass)
    # mark<50 ->0(Fail)

status_matrix=np.where(marks>=50,1,0)
print("Status matrix (1 for Pass, 0 for Fail):\n", status_matrix)

Status matrix (1 for Pass, 0 for Fail):
 [[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [9]:
#Task C2: To standardize failing grades, replace all marks<40 with a value of 0

marks_standardized=np.where(marks<40,0,marks)
print("Standardized marks (failing grades replaced with 0):\n", marks_standardized)

Standardized marks (failing grades replaced with 0):
 [[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


In [10]:
#Task D1: Apply a grading system based on the student Average:
    # Average >=85 -> Grade A(Score: 10)
    # Average >=70 -> Grade B (Score: 8)
    # Average >=50 -> Grade C (Score: 6)
    # Average <50 -> No Grade (Score: 0)

grades=np.where(average_marks_per_student>=85,10,
        np.where((average_marks_per_student>=70),8,
        np.where((average_marks_per_student>=50),6,0)))
print("Grades based on average marks:\n", grades)

Grades based on average marks:
 [ 8  6 10  0  8]


In [11]:
#Task E1: The "Copy vs View" Challenge:
    #Create a backup of the marks array.
    #Modify the original array (e.g., set marks[0,0] to 0).
    #Check if the backup array has changed or not.

backup_marks=marks.copy() 
marks[0,0]=0
print("Original marks array after modification:\n", marks)
print("Backup marks array (should be unchanged):\n", backup_marks)

# if we use marks.view() then backup_marks will change when we modify marks.
# if we do backup=marks then backup_marks will also change when we modify marks.
# but if we use marks.copy() then backup_marks will not change when we modify marks.

Original marks array after modification:
 [[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
Backup marks array (should be unchanged):
 [[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
