In [1]:
import numpy as np


In [2]:
mat=np.array([[1, 2, 3],[4, 5, 6]])
print(mat)


[[1 2 3]
 [4 5 6]]


In [3]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array Properties


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


2
(2, 3)
6
int64


# Type Conversiom

In [7]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [8]:
arr=np.array([3.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[3 2 3]


In [9]:
print(arr[0])
print(arr[-1])

3.2
3.7


# 1D Slicing


In [10]:
print(arr[1:3])
print(arr[:2])
print(arr[:1])

[2.5 3.7]
[3.2 2.5]
[3.2]


# 2D Indexing

In [11]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (mat[0,1])
print(mat[1])

2
[4 5 6]


In [12]:
print(mat[:,1])

[2 5 8]


In [13]:
a=np.array([1,2,3])
b=a #this logic is not safe because it will also change the original array
b[0]=99
print(a)

[99  2  3]


In [14]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [16]:
print(a+b)
print(a-b)
print(a*b)
print(a / b)
print(a+2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[3 4 5]


In [17]:
arr=np.array([1,2,9.16,27])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))





[1.         1.41421356 3.02654919 5.19615242]
[0.         0.69314718 2.21484618 3.29583687]
[2.71828183e+00 7.38905610e+00 9.50905708e+03 5.32048241e+11]
27.0
1.0
9.79
39.16
10.422681996492074


# Broad-Casing Rule


In [18]:
arr=np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [19]:
mat=np.array([[1, 2, 3],[4, 5, 6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


In [20]:
row=np.array([1,2,3])
print(mat + row)


[[2 4 6]
 [5 7 9]]


# Matrix multiplication

In [21]:
A=np.array([[1, 2], [3, 4]])
B=np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


# Random Module

In [22]:
np.random.rand(5)
np.random.rand(3, 3)

array([[0.71916123, 0.6549116 , 0.95286938],
       [0.95702752, 0.27322255, 0.90753969],
       [0.53790146, 0.00424657, 0.56414859]])

In [23]:
np.random.randint(1, 100, 10)

array([98, 86, 69, 25, 70, 38, 30, 17, 35, 26], dtype=int32)

# Reshaping Arrays

In [24]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Axis in NumPy

In [25]:
# Understanding axis in NumPy arrays
# axis=0 means along rows (vertical), axis=1 means along columns (horizontal)

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original 2D array:")
print(arr_2d)
print()

# Sum along axis=0 (sum each column)
print("Sum along axis=0 (columns):", np.sum(arr_2d, axis=0))

# Sum along axis=1 (sum each row)
print("Sum along axis=1 (rows):", np.sum(arr_2d, axis=1))
print()

# Mean along different axes
print("Mean along axis=0:", np.mean(arr_2d, axis=0))
print("Mean along axis=1:", np.mean(arr_2d, axis=1))
print()

# Max and Min along axes
print("Max along axis=0:", np.max(arr_2d, axis=0))
print("Max along axis=1:", np.max(arr_2d, axis=1))

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum along axis=0 (columns): [12 15 18]
Sum along axis=1 (rows): [ 6 15 24]

Mean along axis=0: [4. 5. 6.]
Mean along axis=1: [2. 5. 8.]

Max along axis=0: [7 8 9]
Max along axis=1: [3 6 9]


# Wher in Numpy

In [26]:
# np.where() - Used to filter arrays based on conditions
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Find indices where values are greater than 5
print("Indices where value > 5:", np.where(arr > 5))

# Replace values based on condition (if > 5, replace with 100, else keep original)
result = np.where(arr > 5, 100, arr)
print("Replace values > 5 with 100:", result)

# Multiple conditions - replace odd numbers with -1, even numbers with 1
result2 = np.where(arr % 2 == 0, 1, -1)
print("Even numbers = 1, Odd numbers = -1:", result2)

# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array:")
print(arr_2d)
print("Indices where value > 5:", np.where(arr_2d > 5))

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Indices where value > 5: (array([5, 6, 7, 8, 9]),)
Replace values > 5 with 100: [  1   2   3   4   5 100 100 100 100 100]
Even numbers = 1, Odd numbers = -1: [-1  1 -1  1 -1  1 -1  1 -1  1]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indices where value > 5: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))


# MaX min

In [27]:
mat = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = np.where(mat >= 50, 1, 0)
print("Original matrix:")
print(mat)
print("\nResult (1 if >= 50, else 0):")
print(result)

Original matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Result (1 if >= 50, else 0):
[[0 0 0]
 [0 1 1]
 [1 1 1]]


# Array Creation


In [28]:
cost_price = np.array([1500, 3000, 5000])
print(cost_price)

[1500 3000 5000]


# Array Operation


In [29]:
# Create daily sales matrix (5 days x 3 products)
daily_sales = np.array([[10, 20, 15],
                        [12, 18, 20],
                        [8, 25, 10],
                        [15, 22, 18],
                        [11, 19, 16]])

print("Original Daily Sales:")
print(daily_sales)
print()

# Task 2.1: Add 2 bonus units to every product's daily sale
bonus_sales = daily_sales + 2
print("Task 2.1 - Sales with 2 bonus units:")
print(bonus_sales)
print()

# Task 2.2: Calculate revenue (multiply cost_price by daily_sales)
# Broadcasting: 1D array (3,) multiplied by 2D array (5,3)
revenue = daily_sales * cost_price
print("Task 2.2 - Revenue for each day (broadcasting 1D x 2D):")
print(revenue)
print()

# Task 2.3: Square root of sales data
sales_sqrt = np.sqrt(daily_sales)
print("Task 2.3 - Square root of sales values:")
print(sales_sqrt)

Original Daily Sales:
[[10 20 15]
 [12 18 20]
 [ 8 25 10]
 [15 22 18]
 [11 19 16]]

Task 2.1 - Sales with 2 bonus units:
[[12 22 17]
 [14 20 22]
 [10 27 12]
 [17 24 20]
 [13 21 18]]

Task 2.2 - Revenue for each day (broadcasting 1D x 2D):
[[ 15000  60000  75000]
 [ 18000  54000 100000]
 [ 12000  75000  50000]
 [ 22500  66000  90000]
 [ 16500  57000  80000]]

Task 2.3 - Square root of sales values:
[[3.16227766 4.47213595 3.87298335]
 [3.46410162 4.24264069 4.47213595]
 [2.82842712 5.         3.16227766]
 [3.87298335 4.69041576 4.24264069]
 [3.31662479 4.35889894 4.        ]]


In [30]:
# Phase 1: Array Creation

# Task 1.1: Create cost_price array
cost_price = np.array([1500, 3000, 5000])
print("Task 1.1 - Cost Price Array:")
print(cost_price)
print()

# Task 1.2: Create daily_sales 2D array
daily_sales = np.array([[10, 15, 8, 12],
                        [5, 7, 4, 6],
                        [2, 3, 2, 4]])
print("Task 1.2 - Daily Sales Array:")
print(daily_sales)
print()

# Task 1.3: Print shape and dimension of both arrays
print("Task 1.3 - Array Properties:")
print(f"cost_price - Shape: {cost_price.shape}, Dimension: {cost_price.ndim}")
print(f"daily_sales - Shape: {daily_sales.shape}, Dimension: {daily_sales.ndim}")

Task 1.1 - Cost Price Array:
[1500 3000 5000]

Task 1.2 - Daily Sales Array:
[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]

Task 1.3 - Array Properties:
cost_price - Shape: (3,), Dimension: 1
daily_sales - Shape: (3, 4), Dimension: 2


# Array Operations

In [31]:
# Phase 2: Array Operations (ufuncs)

# Task 2.1: Add 2 bonus units to every product's daily sale
bonus_sales = daily_sales + 2
print("Task 2.1 - Sales with 2 bonus units:")
print(bonus_sales)
print()

# Task 2.2: Calculate total revenue for each day
# Multiply cost_price array by daily_sales matrix
revenue = daily_sales * cost_price.reshape(3, 1)
print("Task 2.2 - Revenue for each product per day:")
print(revenue)
print()

# Total revenue per day (sum across products)
total_revenue_per_day = np.sum(revenue, axis=0)
print("Total revenue per day:")
print(total_revenue_per_day)
print()

# Task 2.3: Use np.sqrt() on sales data
sales_sqrt = np.sqrt(daily_sales)
print("Task 2.3 - Square root of sales values:")
print(sales_sqrt)

Task 2.1 - Sales with 2 bonus units:
[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]

Task 2.2 - Revenue for each product per day:
[[15000 22500 12000 18000]
 [15000 21000 12000 18000]
 [10000 15000 10000 20000]]

Total revenue per day:
[40000 58500 34000 56000]

Task 2.3 - Square root of sales values:
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [33]:
# Phase 3: Slicing and Indexing

# Task 3.1: Access the sales data for Smartwatches (Row 1) for all 4 days
smartwatches_sales = daily_sales[1, :]
print("Task 3.1 - Smartwatches sales for all 4 days:")
print(smartwatches_sales)
print()

# Task 3.2: Access the sales data for all products for the first two days (Monday and Tuesday)
all_products_first_two_days = daily_sales[:, 0:2]
print("Task 3.2 - All products sales for Monday and Tuesday:")
print(all_products_first_two_days)
print()

# Task 3.3: Access the sale of Speakers on Thursday specifically using double indexing
# Speakers is row 2, Thursday is column 3
speakers_thursday = daily_sales[2, 3]
print("Task 3.3 - Speakers sales on Thursday:")
print(speakers_thursday)
print()

# Task 3.4: Extract a 2 × 2 sub-array representing the sales of Headphones and Smartwatches for Monday and Tuesday
# Headphones is row 0, Smartwatches is row 1, Monday is column 0, Tuesday is column 1
headphones_smartwatches_mon_tue = daily_sales[0:2, 0:2]
print("Task 3.4 - Headphones and Smartwatches sales for Monday and Tuesday:")
print(headphones_smartwatches_mon_tue)

Task 3.1 - Smartwatches sales for all 4 days:
[5 7 4 6]

Task 3.2 - All products sales for Monday and Tuesday:
[[10 15]
 [ 5  7]
 [ 2  3]]

Task 3.3 - Speakers sales on Thursday:
4

Task 3.4 - Headphones and Smartwatches sales for Monday and Tuesday:
[[10 15]
 [ 5  7]]


# Reshaping and Linespace

In [35]:
# Phase 4: Reshaping and Linespace

# Task 4.1: Flatten the 3 × 4 daily_sales array to a 1D array of 12 elements using .reshape()
flattened_sales = daily_sales.reshape(12)
print("Task 4.1 - Flattened daily_sales (1D array with 12 elements):")
print(flattened_sales)
print()

# Task 4.2: Convert the sales data into a 2 × 6 matrix
reshaped_sales = daily_sales.reshape(2, 6)
print("Task 4.2 - Reshaped daily_sales into 2 × 6 matrix:")
print(reshaped_sales)
print()

# Task 4.3: Use np.linspace to create an array of 10 equal intervals between 0 and 100 to represent "Discount Percentages"
discount_percentages = np.linspace(0, 100, 10)
print("Task 4.3 - Discount Percentages (10 equal intervals from 0 to 100):")
print(discount_percentages)

Task 4.1 - Flattened daily_sales (1D array with 12 elements):
[10 15  8 12  5  7  4  6  2  3  2  4]

Task 4.2 - Reshaped daily_sales into 2 × 6 matrix:
[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]

Task 4.3 - Discount Percentages (10 equal intervals from 0 to 100):
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


# The Random Module

In [37]:
# Phase 5: The Random Module

# Task 5.1: Use np.random.randint to generate a new 3 × 4 array of "Predicted Sales" 
# for the next week with values ranging from 0 to 20
predicted_sales = np.random.randint(0, 21, size=(3, 4))
print("Predicted Sales (3 × 4 array with values 0-20):")
print(predicted_sales)
print()

# Task 5.2: Generate a random array of 5 numbers between 0 and 1 using np.random.rand
random_decimals = np.random.rand(5)
print("Random array of 5 numbers between 0 and 1:")
print(random_decimals)
print()

# Task 5.3 (Challenge): Use np.sum() to find:
# a) Total items sold over all 4 days
total_items_all_days = np.sum(daily_sales)
print("Total items sold over all 4 days:")
print(total_items_all_days)
print()

# b) Total items sold for each product (Sum across rows)
total_items_per_product = np.sum(daily_sales, axis=1)
print("Total items sold for each product (sum across days):")
print("Headphones:", total_items_per_product[0])
print("Smartwatches:", total_items_per_product[1])
print("Speakers:", total_items_per_product[2])

Predicted Sales (3 × 4 array with values 0-20):
[[19  2  3 12]
 [19  3  3  7]
 [ 3 18 17 10]]

Random array of 5 numbers between 0 and 1:
[0.61396313 0.11839699 0.1458635  0.55883084 0.00525155]

Total items sold over all 4 days:
78

Total items sold for each product (sum across days):
Headphones: 45
Smartwatches: 22
Speakers: 11
