In [1]:
import numpy as np


In [2]:
mat=np.array([[1, 2, 3],[4, 5, 6]])
print(mat)


[[1 2 3]
 [4 5 6]]


In [3]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [4]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Array Properties


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


2
(2, 3)
6
int64


# Type Conversiom

In [7]:
arr=np.array([1,2,3])
print(arr.dtype)

int64


In [8]:
arr=np.array([3.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[3 2 3]


In [9]:
print(arr[0])
print(arr[-1])

3.2
3.7


# 1D Slicing


In [10]:
print(arr[1:3])
print(arr[:2])
print(arr[:1])

[2.5 3.7]
[3.2 2.5]
[3.2]


# 2D Indexing

In [11]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print (mat[0,1])
print(mat[1])

2
[4 5 6]


In [12]:
print(mat[:,1])

[2 5 8]


In [13]:
a=np.array([1,2,3])
b=a #this logic is not safe because it will also change the original array
b[0]=99
print(a)

[99  2  3]


In [14]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [16]:
print(a+b)
print(a-b)
print(a*b)
print(a / b)
print(a+2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[3 4 5]


In [17]:
arr=np.array([1,2,9.16,27])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))





[1.         1.41421356 3.02654919 5.19615242]
[0.         0.69314718 2.21484618 3.29583687]
[2.71828183e+00 7.38905610e+00 9.50905708e+03 5.32048241e+11]
27.0
1.0
9.79
39.16
10.422681996492074


# Broad-Casing Rule


In [18]:
arr=np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [19]:
mat=np.array([[1, 2, 3],[4, 5, 6]])
print(mat + 10)

[[11 12 13]
 [14 15 16]]


In [20]:
row=np.array([1,2,3])
print(mat + row)


[[2 4 6]
 [5 7 9]]


# Matrix multiplication

In [24]:
A=np.array([[1, 2], [3, 4]])
B=np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


# Random Module

In [26]:
np.random.rand(5)
np.random.rand(3, 3)

array([[0.15428321, 0.54266261, 0.246092  ],
       [0.66253971, 0.88080531, 0.5759303 ],
       [0.47790553, 0.15819052, 0.01643844]])

In [28]:
np.random.randint(1, 100, 10)

array([15, 40, 45, 14, 15, 83,  3,  8, 27, 66], dtype=int32)

# Reshaping Arrays

In [30]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Axis in NumPy

In [31]:
# Understanding axis in NumPy arrays
# axis=0 means along rows (vertical), axis=1 means along columns (horizontal)

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original 2D array:")
print(arr_2d)
print()

# Sum along axis=0 (sum each column)
print("Sum along axis=0 (columns):", np.sum(arr_2d, axis=0))

# Sum along axis=1 (sum each row)
print("Sum along axis=1 (rows):", np.sum(arr_2d, axis=1))
print()

# Mean along different axes
print("Mean along axis=0:", np.mean(arr_2d, axis=0))
print("Mean along axis=1:", np.mean(arr_2d, axis=1))
print()

# Max and Min along axes
print("Max along axis=0:", np.max(arr_2d, axis=0))
print("Max along axis=1:", np.max(arr_2d, axis=1))

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum along axis=0 (columns): [12 15 18]
Sum along axis=1 (rows): [ 6 15 24]

Mean along axis=0: [4. 5. 6.]
Mean along axis=1: [2. 5. 8.]

Max along axis=0: [7 8 9]
Max along axis=1: [3 6 9]


# Wher in Numpy

In [32]:
# np.where() - Used to filter arrays based on conditions
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Find indices where values are greater than 5
print("Indices where value > 5:", np.where(arr > 5))

# Replace values based on condition (if > 5, replace with 100, else keep original)
result = np.where(arr > 5, 100, arr)
print("Replace values > 5 with 100:", result)

# Multiple conditions - replace odd numbers with -1, even numbers with 1
result2 = np.where(arr % 2 == 0, 1, -1)
print("Even numbers = 1, Odd numbers = -1:", result2)

# 2D array example
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array:")
print(arr_2d)
print("Indices where value > 5:", np.where(arr_2d > 5))

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Indices where value > 5: (array([5, 6, 7, 8, 9]),)
Replace values > 5 with 100: [  1   2   3   4   5 100 100 100 100 100]
Even numbers = 1, Odd numbers = -1: [-1  1 -1  1 -1  1 -1  1 -1  1]

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indices where value > 5: (array([1, 2, 2, 2]), array([2, 0, 1, 2]))


# MaX min

In [33]:
mat = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = np.where(mat >= 50, 1, 0)
print("Original matrix:")
print(mat)
print("\nResult (1 if >= 50, else 0):")
print(result)

Original matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Result (1 if >= 50, else 0):
[[0 0 0]
 [0 1 1]
 [1 1 1]]
