# Exercise 2

In [2]:
import numpy as np

# Initialize the data as a 2D NumPy array named marks
# 5 students × 3 subjects
marks = np.array([[78, 85, 90],
                  [45, 60, 55],
                  [88, 92, 95],
                  [30, 40, 35],
                  [65, 70, 75]])

print("Marks array (5 students × 3 subjects):")
print(marks)

Marks array (5 students × 3 subjects):
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [3]:
# PART A: Basic Level (Exploration)

# Task A1: Metadata Discovery
print("Task A1: Metadata Discovery")
print("="*50)

# Determine the Shape of the array
print(f"Shape of the array: {marks.shape}")

# Find the Total Number of elements
print(f"Total number of elements: {marks.size}")

# Identify the Data Type of the elements
print(f"Data type of elements: {marks.dtype}")
print()

# Task A2: Data Indexing & Slicing
print("Task A2: Data Indexing & Slicing")
print("="*50)

# Extract all marks for the 2nd student (index 1)
student_2_marks = marks[1, :]
print(f"All marks for 2nd student: {student_2_marks}")

# Extract all marks for the 3rd subject across all students (column index 2)
subject_3_marks = marks[:, 2]
print(f"All marks for 3rd subject (across all students): {subject_3_marks}")

# Find the specific mark for Student 1 in Subject 2 (row 0, column 1)
student_1_subject_2 = marks[0, 1]
print(f"Student 1's mark in Subject 2: {student_1_subject_2}")

Task A1: Metadata Discovery
Shape of the array: (5, 3)
Total number of elements: 15
Data type of elements: int64

Task A2: Data Indexing & Slicing
All marks for 2nd student: [45 60 55]
All marks for 3rd subject (across all students): [90 55 95 35 75]
Student 1's mark in Subject 2: 85


In [4]:
# PART B: (Analysis)

# Task B1: Means and Averages
print("Task B1: Means and Averages")
print("="*50)

# Calculate the average marks for each student (average across columns, axis=1)
average_per_student = np.mean(marks, axis=1)
print("Average marks for each student:")
for i, avg in enumerate(average_per_student):
    print(f"  Student {i+1}: {avg:.2f}")
print()

# Calculate the average marks for each subject (average across rows, axis=0)
average_per_subject = np.mean(marks, axis=0)
print("Average marks for each subject:")
for i, avg in enumerate(average_per_subject):
    print(f"  Subject {i+1}: {avg:.2f}")
print()

# Task B2: Filtering Top Performers
print("Task B2: Filtering Top Performers")
print("="*50)

# Identify and display students whose average marks are >= 80
top_performers = np.where(average_per_student >= 80)[0]
print("Students with average marks >= 80:")
for student_idx in top_performers:
    print(f"  Student {student_idx+1}: Average = {average_per_student[student_idx]:.2f}")
print()

# Task B3: Global Adjustments
print("Task B3: Global Adjustments")
print("="*50)

# Add 5 grace marks to every subject for every student using broadcasting
print("Original marks:")
print(marks)
print()

marks_adjusted = marks + 5
print("Marks after adding 5 grace marks:")
print(marks_adjusted)

Task B1: Means and Averages
Average marks for each student:
  Student 1: 84.33
  Student 2: 53.33
  Student 3: 91.67
  Student 4: 35.00
  Student 5: 70.00

Average marks for each subject:
  Subject 1: 61.20
  Subject 2: 69.40
  Subject 3: 70.00

Task B2: Filtering Top Performers
Students with average marks >= 80:
  Student 1: Average = 84.33
  Student 3: Average = 91.67

Task B3: Global Adjustments
Original marks:
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]

Marks after adding 5 grace marks:
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [5]:
# PART D: Performance Scoring

# Task D1: Grade Allocation - Apply a grading system based on the Student Average
print("Task D1: Grade Allocation")
print("="*50)

scores = np.where(average_per_student >= 85, 10,
                  np.where(average_per_student >= 70, 8,
                          np.where(average_per_student >= 50, 6, 0)))

grades = np.where(average_per_student >= 85, 'A',
                  np.where(average_per_student >= 70, 'B',
                          np.where(average_per_student >= 50, 'C', 'No Grade')))

print("Student Performance Report:")
print("-" * 50)
for i in range(len(average_per_student)):
    print(f"Student {i+1}: Average = {average_per_student[i]:.2f} | Grade = {grades[i]} | Score = {scores[i]}")

Task D1: Grade Allocation
Student Performance Report:
--------------------------------------------------
Student 1: Average = 84.33 | Grade = B | Score = 8
Student 2: Average = 53.33 | Grade = C | Score = 6
Student 3: Average = 91.67 | Grade = A | Score = 10
Student 4: Average = 35.00 | Grade = No Grade | Score = 0
Student 5: Average = 70.00 | Grade = B | Score = 8


In [6]:
# PART E: Data Integrity

# Task E1: The "Copy vs View" Challenge
print("Task E1: The 'Copy vs View' Challenge")
print("="*50)

# Step 1: Create a backup of the marks array using .copy()
backup = marks.copy()
print("Step 1: Created a proper backup using .copy()")
print("Original marks array:")
print(marks)
print("\nBackup array:")
print(backup)
print()

# Step 2: Modify the original array (set marks[0, 0] = 0)
print("Step 2: Modifying the original array (marks[0, 0] = 0)")
marks[0, 0] = 0
print("Modified marks array:")
print(marks)
print()

# Step 3: Check if the backup array changed or remained original
print("Step 3: Checking if backup array changed or remained original")
print("Backup array:")
print(backup)
print()

if backup[0, 0] == 78:
    print("✓ SUCCESS: Backup array remained unchanged (backup[0, 0] = 78)")
else:
    print("✗ FAILED: Backup array was also modified")


Task E1: The 'Copy vs View' Challenge
Step 1: Created a proper backup using .copy()
Original marks array:
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]

Backup array:
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]

Step 2: Modifying the original array (marks[0, 0] = 0)
Modified marks array:
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]

Step 3: Checking if backup array changed or remained original
Backup array:
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]

✓ SUCCESS: Backup array remained unchanged (backup[0, 0] = 78)


# Array Creation and Inspection


In [ ]:
np.random.sled(0)  # For reproducibility
random_marks = np.random.randint(0, 101, size=(5, 3))
print("Randomly generated marks for 5 students and 3 subjects:")
print(random_marks)


Randomly generated marks for 5 students and 3 subjects:
[[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]
 [88 12 58]]
